version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Choose either one of the orbs below
#   # welcome: circleci/welcome-orb@0.4.1
#   aws-cli: circleci/aws-cli@2.0.3
# # Define the jobs we want to run for this project
jobs:

  create_infrastructure:  # a job step that automatically creates infrastructure
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: | # note that this formation is for cloudformation using DEPLOY not CREATE so the syntax is different 
            aws cloudformation deploy --template-file template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
      # Fail the job intentionally to simulate an error.
      # Uncomment the line below if you want to fail the current step
      # - run: return 1
      # - destroy_environment
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure